apiVersion: agentregistry.dev/v1alpha1
kind: DiscoveryConfig
metadata:
  name: abox
  namespace: agentregistry
spec:
  environments:
    - name: abox
      cluster:
        name: abox
        useWorkloadIdentity: false
      discoveryEnabled: true
      namespaces:
        - default
        - kagent
        - agentgateway-system
