apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - kagent.yaml
  - ai-agent.yaml
  - db-mcp.yaml
  - db-expert-agent.yaml
  - agentregistry-discoveryconfig.yaml
  - mcpg.yaml
  - qdrant.yaml