apiVersion: v1
kind: Namespace
metadata:
  name: phoenix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: phoenix
  namespace: flux-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/arizephoenix/phoenix-helm
  ref:
    tag: "7.0.13"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phoenix
  namespace: phoenix
spec:
  interval: 24h
  releaseName: phoenix
  chartRef:
    kind: OCIRepository
    name: phoenix
    namespace: flux-system
  install:
    createNamespace: true
